// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PawPrints.Api.Data;

#nullable disable

namespace PawPrints.Api.Data.Migrations
{
    [DbContext(typeof(PawPrintsDbContext))]
    [Migration("20260505120000_AddPredictionsAndNotificationOutbox")]
    partial class AddPredictionsAndNotificationOutbox
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("PawPrints.Api.Data.NotificationOutboxItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PredictionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SendAfterUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PredictionId");

                    b.HasIndex("UserId", "SendAfterUtc");

                    b.ToTable("NotificationOutbox");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PawPrintsInvite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("ConsumedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedByUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PawPrintsUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<long?>("CollaboratesWithUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratesWithUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PuppyEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ClientEventId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateOnly>("DateKey")
                        .HasMaxLength(10)
                        .HasColumnType("date");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientEventId")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PuppyPrediction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("BestGuessAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ExplanationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastEvaluatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PredictedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("TriggerEventClientId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("WindowEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("WindowStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TriggerEventClientId");

                    b.HasIndex("UserId", "Type", "Status");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("PawPrints.Api.Data.NotificationOutboxItem", b =>
                {
                    b.HasOne("PawPrints.Api.Data.PuppyPrediction", "Prediction")
                        .WithMany("Notifications")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawPrints.Api.Data.PawPrintsUser", "User")
                        .WithMany("NotificationOutboxItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prediction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PawPrintsInvite", b =>
                {
                    b.HasOne("PawPrints.Api.Data.PawPrintsUser", "ConsumedBy")
                        .WithMany()
                        .HasForeignKey("ConsumedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PawPrints.Api.Data.PawPrintsUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumedBy");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PawPrintsUser", b =>
                {
                    b.HasOne("PawPrints.Api.Data.PawPrintsUser", "CollaboratesWith")
                        .WithMany("Collaborators")
                        .HasForeignKey("CollaboratesWithUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CollaboratesWith");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PuppyEvent", b =>
                {
                    b.HasOne("PawPrints.Api.Data.PawPrintsUser", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PuppyPrediction", b =>
                {
                    b.HasOne("PawPrints.Api.Data.PawPrintsUser", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PawPrintsUser", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("Events");

                    b.Navigation("NotificationOutboxItems");

                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PuppyPrediction", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
