// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PawPrints.Api.Data;

#nullable disable

namespace PawPrints.Api.Data.Migrations
{
    [DbContext(typeof(PawPrintsDbContext))]
    [Migration("20260505110000_ReclassifyEarlierDailySleepsAsNaps")]
    partial class ReclassifyEarlierDailySleepsAsNaps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("PawPrints.Api.Data.PawPrintsInvite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("ConsumedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedByUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PawPrintsUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CollaboratesWithUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratesWithUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PuppyEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientEventId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateKey")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientEventId")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PawPrintsInvite", b =>
                {
                    b.HasOne("PawPrints.Api.Data.PawPrintsUser", "ConsumedBy")
                        .WithMany()
                        .HasForeignKey("ConsumedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PawPrints.Api.Data.PawPrintsUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumedBy");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PawPrintsUser", b =>
                {
                    b.HasOne("PawPrints.Api.Data.PawPrintsUser", "CollaboratesWith")
                        .WithMany("Collaborators")
                        .HasForeignKey("CollaboratesWithUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CollaboratesWith");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PuppyEvent", b =>
                {
                    b.HasOne("PawPrints.Api.Data.PawPrintsUser", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PawPrints.Api.Data.PawPrintsUser", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
